/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime false --config wrangler.json` (hash: aa92612b7019134f98f6346bab6ff40a)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	TELEGRAM_QUEUE: Queue;
	CF_VERSION_METADATA: WorkerVersionMetadata;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
