"use client";
import { useState } from "react";

type Grant = { userId: string; email: string; displayName: string | null };
export function ExclusiveAccessManager({ profileId, initialGrants }: { profileId: string; initialGrants: Grant[] }) {
  const [grants, setGrants] = useState(initialGrants); const [email, setEmail] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  async function add(event: React.FormEvent) { event.preventDefault(); setBusy(true); setNotice(""); try { const response = await fetch(`/api/perfiles/${profileId}/exclusive-access`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email }) }); const payload = await response.json() as { error?: string; grant?: Grant }; if (!response.ok || !payload.grant) throw new Error(payload.error ?? "No se pudo autorizar la cuenta."); setGrants((items) => items.some((item) => item.userId === payload.grant!.userId) ? items : [...items, payload.grant!]); setEmail(""); setNotice("La cuenta ya puede ver el contenido exclusivo de este anuncio."); } catch (cause) { setNotice(cause instanceof Error ? cause.message : "No se pudo autorizar la cuenta."); } finally { setBusy(false); } }
  async function remove(userId: string) { setBusy(true); const response = await fetch(`/api/perfiles/${profileId}/exclusive-access`, { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ userId }) }); if (response.ok) { setGrants((items) => items.filter((item) => item.userId !== userId)); setNotice("Acceso retirado."); } else setNotice("No se pudo retirar el acceso."); setBusy(false); }
  return <section className="exclusive-access-manager"><div><p className="eyebrow">ACCESO EXCLUSIVO</p><h2>Personas autorizadas</h2><p>El pago y acuerdo se realizan directamente fuera de Chile3X. Aquí solo autorizas una cuenta registrada mediante su correo.</p></div><form onSubmit={add}><label>Correo de la cuenta<input type="email" required maxLength={254} value={email} onChange={(event) => setEmail(event.target.value)} placeholder="persona@correo.cl" /></label><button className="button button-primary" disabled={busy}>Autorizar</button></form>{notice && <p role="status">{notice}</p>}{grants.length > 0 && <div className="exclusive-grant-list">{grants.map((grant) => <article key={grant.userId}><div><strong>{grant.displayName || "Usuario Chile3X"}</strong><span>{grant.email}</span></div><button type="button" disabled={busy} onClick={() => remove(grant.userId)}>Quitar acceso</button></article>)}</div>}</section>;
}
