import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { DirectoryShell } from "@/app/directorio/_components";
import { getNewsBySlug, textFromHtml } from "@/lib/news";
import { safeJsonLd } from "@/lib/json-ld";
import { socialCardImageUrl } from "@/lib/seo";

export const dynamic = "force-dynamic";
type Props = { params: Promise<{ slug: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const row = await getNewsBySlug(slug); if (!row) return {}; const { post, cover } = row; const description = post.metaDescription || post.excerpt || textFromHtml(post.contentHtml).slice(0, 160); const image = cover ? `/noticias/media/${cover.id}` : socialCardImageUrl; return { title: post.seoTitle || post.title, description, alternates: { canonical: post.canonicalUrl || `/noticias/${post.slug}` }, robots: post.noindex ? { index: false, follow: true } : undefined, openGraph: { title: post.ogTitle || post.seoTitle || post.title, description: post.ogDescription || description, url: `/noticias/${post.slug}`, type: "article", siteName: "Chile3X", images: [image] }, twitter: { card: "summary_large_image", title: post.ogTitle || post.title, description: post.ogDescription || description, images: [image] } }; }
export default async function NewsArticlePage({ params }: Props) { const { slug } = await params; const row = await getNewsBySlug(slug); if (!row) notFound(); const { post, cover } = row; const schema = { "@context": "https://schema.org", "@type": "Article", headline: post.title, description: post.metaDescription || post.excerpt, datePublished: post.publishedAt, dateModified: post.updatedAt, publisher: { "@type": "Organization", name: "Chile3X", url: "https://chile3x.cl" }, mainEntityOfPage: `https://chile3x.cl/noticias/${post.slug}`, ...(cover ? { image: `https://chile3x.cl/noticias/media/${cover.id}` } : {}) }; return <DirectoryShell><main className="news-article"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJsonLd(schema) }} /><Link className="page-back-link" href="/noticias">← Volver a noticias</Link><header><p className="eyebrow">NOTICIAS CHILE3X</p><h1>{post.title}</h1><p>{post.excerpt}</p><time dateTime={post.publishedAt ?? post.createdAt}>{new Intl.DateTimeFormat("es-CL", { dateStyle: "long" }).format(new Date(post.publishedAt ?? post.createdAt))}</time></header>{cover && <figure className="news-article-cover"><Image src={`/noticias/media/${cover.id}`} alt={post.title} fill priority unoptimized sizes="100vw" /></figure>}<article className="news-article-content" dangerouslySetInnerHTML={{ __html: post.contentHtml }} /><footer><h2>Explora Chile3X</h2><p>Encuentra publicaciones por ciudad o crea una cuenta para anunciarte en nuestro directorio nacional.</p><div><Link className="button button-primary" href="/escorts">Ver escorts en Chile</Link><Link className="button button-outline" href="/registro">Crear cuenta</Link></div></footer></main></DirectoryShell>; }
